In [1]:
!pip install -q transformers datasets evaluate accelerate sentencepiece

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 3.0 MB/s eta 0:00:00

In [3]:
import os
import random
import numpy as np
from datasets import load_dataset
from transformers import (
    AutoTokenizer,
    AutoModelForSeq2SeqLM,
    DataCollatorForSeq2Seq,
    Seq2SeqTrainingArguments,
    Seq2SeqTrainer,
    set_seed,
)
import evaluate

In [4]:
from datasets import load_dataset
from transformers import (
    AutoTokenizer,
    AutoModelForSeq2SeqLM,
    DataCollatorForSeq2Seq,
    Seq2SeqTrainer,
    Seq2SeqTrainingArguments
)
import numpy as np
import evaluate
import torch

In [7]:
TRAIN_PATH = "/content/train.csv"
VAL_PATH = "/content/validation.csv"
TEST_PATH = "/content/test.csv"

In [9]:
import pandas as pd

train_path = "/content/train.csv"

# Robust loading: the python engine handles irregular quotes better
df_train = pd.read_csv(train_path,
                       engine="python",
                       on_bad_lines="skip",
                       quoting=3,          # ignore weird quote mismatches
                       encoding_errors="ignore")  # skip invalid chars

print("✅ Train loaded:", df_train.shape)

✅ Train loaded: (196620, 3)

In [10]:
df_val = pd.read_csv("/content/validation.csv", engine="python", on_bad_lines="skip", quoting=3, encoding_errors="ignore")
df_test = pd.read_csv("/content/test.csv", engine="python", on_bad_lines="skip", quoting=3, encoding_errors="ignore")

print("Val:", df_val.shape)
print("Test:", df_test.shape)

Val: (47854, 3)
Test: (37030, 3)

In [11]:
df_train.to_csv("/content/train_clean.csv", index=False)
df_val.to_csv("/content/validation_clean.csv", index=False)
df_test.to_csv("/content/test_clean.csv", index=False)

In [12]:
from datasets import load_dataset

data_files = {
    "train": "/content/train_clean.csv",
    "validation": "/content/validation_clean.csv",
    "test": "/content/test_clean.csv",
}

dataset = load_dataset("csv", data_files=data_files)
print(dataset)

Generating train split: 0 examples [00:00, ? examples/s]

Generating validation split: 0 examples [00:00, ? examples/s]

Generating test split: 0 examples [00:00, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['id', 'article', 'highlights'],
        num_rows: 196620
    })
    validation: Dataset({
        features: ['id', 'article', 'highlights'],
        num_rows: 47854
    })
    test: Dataset({
        features: ['id', 'article', 'highlights'],
        num_rows: 37030
    })
})

In [13]:
import csv

fixed_path = "/content/train_fixed.csv"
with open(train_path, "r", encoding="utf-8", errors="ignore") as infile, \
     open(fixed_path, "w", encoding="utf-8") as outfile:
    for line in infile:
        # remove unbalanced quotes (odd number of ")
        if line.count('"') % 2 != 0:
            line = line.replace('"', '')
        outfile.write(line)

print("✅ Wrote sanitized file:", fixed_path)

✅ Wrote sanitized file: /content/train_fixed.csv

In [14]:
df_train = pd.read_csv(fixed_path, engine="python", on_bad_lines="skip")
print(df_train.shape)

(299828, 3)

In [15]:
from datasets import Dataset, DatasetDict

dataset = DatasetDict({
    "train": Dataset.from_pandas(df_train),
    "validation": Dataset.from_pandas(df_val),
    "test": Dataset.from_pandas(df_test)
})

print(dataset)

DatasetDict({
    train: Dataset({
        features: ['id', 'article', 'highlights', '__index_level_0__', '__index_level_1__', '__index_level_2__', '__index_level_3__', '__index_level_4__', '__index_level_5__', '__index_level_6__', '__index_level_7__', '__index_level_8__', '__index_level_9__'],
        num_rows: 299828
    })
    validation: Dataset({
        features: ['id', 'article', 'highlights', '__index_level_0__', '__index_level_1__', '__index_level_2__', '__index_level_3__', '__index_level_4__', '__index_level_5__', '__index_level_6__', '__index_level_7__', '__index_level_8__', '__index_level_9__', '__index_level_10__', '__index_level_11__', '__index_level_12__', '__index_level_13__', '__index_level_14__', '__index_level_15__', '__index_level_16__', '__index_level_17__', '__index_level_18__', '__index_level_19__', '__index_level_20__', '__index_level_21__', '__index_level_22__', '__index_level_23__'],
        num_rows: 47854
    })
    test: Dataset({
        features: ['id', 'article', 'highlights', '__index_level_0__', '__index_level_1__', '__index_level_2__', '__index_level_3__', '__index_level_4__', '__index_level_5__', '__index_level_6__', '__index_level_7__', '__index_level_8__', '__index_level_9__', '__index_level_10__', '__index_level_11__', '__index_level_12__', '__index_level_13__', '__index_level_14__', '__index_level_15__', '__index_level_16__', '__index_level_17__', '__index_level_18__'],
        num_rows: 37030
    })
})

In [17]:
from transformers import AutoTokenizer

# Load the tokenizer
tokenizer = AutoTokenizer.from_pretrained("t5-small")

# Define input/output sequence lengths
MAX_INPUT_LENGTH = 512
MAX_TARGET_LENGTH = 150

# Define the preprocessing/tokenization function
def preprocess_function(examples):
    # 1️⃣ Add the "summarize:" prefix required by T5
    inputs = ["summarize: " + doc for doc in examples["article"]]

    # 2️⃣ Tokenize the input text
    model_inputs = tokenizer(
        inputs,
        max_length=MAX_INPUT_LENGTH,
        truncation=True,
        padding="max_length",
    )

    # 3️⃣ Tokenize the summaries as targets
    with tokenizer.as_target_tokenizer():
        labels = tokenizer(
            examples["highlights"],
            max_length=MAX_TARGET_LENGTH,
            truncation=True,
            padding="max_length",
        )["input_ids"]

    # 4️⃣ Replace pad token ids with -100 (ignored in loss)
    labels = [
        [(label if label != tokenizer.pad_token_id else -100) for label in l]
        for l in labels
    ]
    model_inputs["labels"] = labels
    return model_inputs

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

tokenizer_config.json:   0%|          | 0.00/2.32k [00:00<?, ?B/s]

spiece.model:   0%|          | 0.00/792k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.39M [00:00<?, ?B/s]

In [19]:
def preprocess_function(examples):
    # Safely handle missing or NaN values
    clean_articles = []
    clean_summaries = []

    for art, summ in zip(examples["article"], examples["highlights"]):
        # Convert None/NaN to empty string
        if art is None or not isinstance(art, str) or art.strip() == "":
            art = ""
        if summ is None or not isinstance(summ, str) or summ.strip() == "":
            summ = ""

        clean_articles.append("summarize: " + art)
        clean_summaries.append(summ)

    # Tokenize input
    model_inputs = tokenizer(
        clean_articles,
        max_length=MAX_INPUT_LENGTH,
        truncation=True,
        padding="max_length",
    )

    # Tokenize output
    with tokenizer.as_target_tokenizer():
        labels = tokenizer(
            clean_summaries,
            max_length=MAX_TARGET_LENGTH,
            truncation=True,
            padding="max_length",
        )["input_ids"]

    # Replace pad token ids with -100 so they're ignored in loss
    labels = [
        [(label if label != tokenizer.pad_token_id else -100) for label in l]
        for l in labels
    ]
    model_inputs["labels"] = labels
    return model_inputs

In [20]:
tokenized_datasets = dataset.map(
    preprocess_function,
    batched=True,
    remove_columns=dataset["train"].column_names
)

Map:   0%|          | 0/299828 [00:00<?, ? examples/s]

/usr/local/lib/python3.12/dist-packages/transformers/tokenization_utils_base.py:4034: UserWarning: `as_target_tokenizer` is deprecated and will be removed in v5 of Transformers. You can tokenize your labels by using the argument `text_target` of the regular `__call__` method (either in the same call as your input texts if you use the same keyword arguments, or in a separate call.
  warnings.warn(

Map:   0%|          | 0/47854 [00:00<?, ? examples/s]

Map:   0%|          | 0/37030 [00:00<?, ? examples/s]

In [21]:
import pandas as pd
missing_articles = df_train['article'].isna().sum()
missing_highlights = df_train['highlights'].isna().sum()
print(f"Missing articles: {missing_articles}, Missing summaries: {missing_highlights}")

Missing articles: 297021, Missing summaries: 298336

In [22]:
import pandas as pd

df_train = pd.read_csv("/content/train.csv", engine="python", on_bad_lines="skip", quoting=3, encoding_errors="ignore")
print(df_train.head(5))
print(df_train.columns)

                                                                                                                                                                                                                                                                                                                                                                                                                                                               id  \
0001d1afc246a7964130f43ae940af6bc6c57f01           "By . Associated Press . PUBLISHED: . 14:11 EST     25 October 2013 . | . UPDATED: . 15:36 EST  25 October 2013 . The bishop of the Fargo Cath...  Grand Forks and Jamestown to the hepatitis A v...  Grand Forks and Jamestown to the hepatitis A ....  but officials feel it's important to alert peo...  tiredness  loss of appetite  nausea and abdominal discomfort. Fargo Catholi...  "Bishop John Folda
He contracted the infection through contaminate... NaN                                                NaN                                         NaN                                                NaN                                                NaN                                                NaN                                                NaN        NaN               NaN                                                               None
Church members in Fargo                             Grand Forks and Jamestown could have been expo... NaN                                         NaN                                                NaN                                                NaN                                                NaN                                                NaN        NaN               NaN                                                               None
Ralph Mata                                          an internal affairs lieutenant                     allegedly helped group get guns .          NaN                                                NaN                                                NaN                                                NaN                                                NaN        NaN               NaN                                                               None
He also arranged to pay two assassins in a murd...  a complaint alleges ."                            NaN                                         NaN                                                NaN                                                NaN                                                NaN                                                NaN        NaN               NaN                                                               None

                                                                                                                                                                                                                                                                                                                                                                                                                                                        article  \
0001d1afc246a7964130f43ae940af6bc6c57f01           "By . Associated Press . PUBLISHED: . 14:11 EST     25 October 2013 . | . UPDATED: . 15:36 EST  25 October 2013 . The bishop of the Fargo Cath...  Grand Forks and Jamestown to the hepatitis A v...  Grand Forks and Jamestown to the hepatitis A ....  but officials feel it's important to alert peo...  tiredness  loss of appetite  nausea and abdominal discomfort. Fargo Catholi...   of North Dakota
He contracted the infection through contaminate... NaN                                                NaN                                         NaN                                                NaN                                                NaN                                                NaN                                                NaN        NaN               NaN                                                             None
Church members in Fargo                             Grand Forks and Jamestown could have been expo... NaN                                         NaN                                                NaN                                                NaN                                                NaN                                                NaN        NaN               NaN                                                             None
Ralph Mata                                          an internal affairs lieutenant                     allegedly helped group get guns .          NaN                                                NaN                                                NaN                                                NaN                                                NaN        NaN               NaN                                                             None
He also arranged to pay two assassins in a murd...  a complaint alleges ."                            NaN                                         NaN                                                NaN                                                NaN                                                NaN                                                NaN        NaN               NaN                                                             None

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                highlights
0001d1afc246a7964130f43ae940af6bc6c57f01           "By . Associated Press . PUBLISHED: . 14:11 EST     25 October 2013 . | . UPDATED: . 15:36 EST  25 October 2013 . The bishop of the Fargo Cath...  Grand Forks and Jamestown to the hepatitis A v...  Grand Forks and Jamestown to the hepatitis A ....  but officials feel it's important to alert peo...  tiredness  loss of appetite  nausea and abdominal discomfort. Fargo Catholi...   is taking time off after being diagnosed .
He contracted the infection through contaminate... NaN                                                NaN                                         NaN                                                NaN                                                NaN                                                NaN                                                NaN        NaN               NaN                                                                                        None
Church members in Fargo                             Grand Forks and Jamestown could have been expo... NaN                                         NaN                                                NaN                                                NaN                                                NaN                                                NaN        NaN               NaN                                                                                        None
Ralph Mata                                          an internal affairs lieutenant                     allegedly helped group get guns .          NaN                                                NaN                                                NaN                                                NaN                                                NaN        NaN               NaN                                                                                        None
He also arranged to pay two assassins in a murd...  a complaint alleges ."                            NaN                                         NaN                                                NaN                                                NaN                                                NaN                                                NaN        NaN               NaN                                                                                        None
Index(['id', 'article', 'highlights'], dtype='object')

In [23]:
['article', 'highlights']

['article', 'highlights']

In [24]:
df_clean = df_train.dropna(subset=['article', 'highlights'])
df_clean = df_clean[df_clean['article'].str.strip() != ""]
df_clean = df_clean[df_clean['highlights'].str.strip() != ""]

print("✅ Cleaned dataset shape:", df_clean.shape)

✅ Cleaned dataset shape: (4035, 3)

In [25]:
# ============================================
# 🧠 Fine-tuning T5-small on cleaned dataset
# ============================================
import torch
from datasets import Dataset, DatasetDict
from transformers import (
    AutoTokenizer,
    AutoModelForSeq2SeqLM,
    DataCollatorForSeq2Seq,
    Seq2SeqTrainer,
    Seq2SeqTrainingArguments
)
import numpy as np
import evaluate

# ✅ Use your cleaned pandas DataFrames
# (Assume df_clean already exists)
# We'll split it manually into train/val/test
from sklearn.model_selection import train_test_split

train_df, val_df = train_test_split(df_clean, test_size=0.2, random_state=42)
test_df, val_df = train_test_split(val_df, test_size=0.5, random_state=42)

dataset = DatasetDict({
    "train": Dataset.from_pandas(train_df),
    "validation": Dataset.from_pandas(val_df),
    "test": Dataset.from_pandas(test_df),
})

print(dataset)

# ==========================
# ⚙️ Tokenization
# ==========================
tokenizer = AutoTokenizer.from_pretrained("t5-small")

MAX_INPUT_LENGTH = 512
MAX_TARGET_LENGTH = 150

def preprocess_function(examples):
    clean_articles = []
    clean_summaries = []
    for art, summ in zip(examples["article"], examples["highlights"]):
        if art is None or not isinstance(art, str) or art.strip() == "":
            art = ""
        if summ is None or not isinstance(summ, str) or summ.strip() == "":
            summ = ""
        clean_articles.append("summarize: " + art)
        clean_summaries.append(summ)

    model_inputs = tokenizer(
        clean_articles,
        max_length=MAX_INPUT_LENGTH,
        truncation=True,
        padding="max_length"
    )
    with tokenizer.as_target_tokenizer():
        labels = tokenizer(
            clean_summaries,
            max_length=MAX_TARGET_LENGTH,
            truncation=True,
            padding="max_length"
        )["input_ids"]
    labels = [[(l if l != tokenizer.pad_token_id else -100) for l in label] for label in labels]
    model_inputs["labels"] = labels
    return model_inputs

tokenized_datasets = dataset.map(
    preprocess_function,
    batched=True,
    remove_columns=dataset["train"].column_names
)

# ==========================
# 🧩 Model setup
# ==========================
model = AutoModelForSeq2SeqLM.from_pretrained("t5-small")
data_collator = DataCollatorForSeq2Seq(tokenizer, model=model)

rouge = evaluate.load("rouge")

def postprocess_text(preds, labels):
    preds = [p.strip() for p in preds]
    labels = [l.strip() for l in labels]
    return preds, labels

def compute_metrics(eval_preds):
    preds, labels = eval_preds
    if isinstance(preds, tuple):
        preds = preds[0]
    decoded_preds = tokenizer.batch_decode(preds, skip_special_tokens=True)
    labels = np.where(labels != -100, labels, tokenizer.pad_token_id)
    decoded_labels = tokenizer.batch_decode(labels, skip_special_tokens=True)
    decoded_preds, decoded_labels = postprocess_text(decoded_preds, decoded_labels)
    result = rouge.compute(predictions=decoded_preds, references=decoded_labels, use_stemmer=True)
    result = {k: round(v.mid.fmeasure * 100, 4) for k, v in result.items()}
    prediction_lens = [np.count_nonzero(p != tokenizer.pad_token_id) for p in preds]
    result["gen_len"] = np.mean(prediction_lens)
    return result

# ==========================
# ⚡ Training
# ==========================
training_args = Seq2SeqTrainingArguments(
    output_dir="./t5_cleaned_small",
    evaluation_strategy="epoch",
    learning_rate=5e-5,
    per_device_train_batch_size=4,
    per_device_eval_batch_size=8,
    weight_decay=0.01,
    save_total_limit=2,
    num_train_epochs=1,   # full training: increase to 3 if GPU allows
    predict_with_generate=True,
    fp16=torch.cuda.is_available(),
)

trainer = Seq2SeqTrainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_datasets["train"],
    eval_dataset=tokenized_datasets["validation"],
    tokenizer=tokenizer,
    data_collator=data_collator,
    compute_metrics=compute_metrics,
)

trainer.train()

DatasetDict({
    train: Dataset({
        features: ['id', 'article', 'highlights', '__index_level_0__', '__index_level_1__', '__index_level_2__', '__index_level_3__', '__index_level_4__', '__index_level_5__', '__index_level_6__', '__index_level_7__', '__index_level_8__', '__index_level_9__'],
        num_rows: 3228
    })
    validation: Dataset({
        features: ['id', 'article', 'highlights', '__index_level_0__', '__index_level_1__', '__index_level_2__', '__index_level_3__', '__index_level_4__', '__index_level_5__', '__index_level_6__', '__index_level_7__', '__index_level_8__', '__index_level_9__'],
        num_rows: 404
    })
    test: Dataset({
        features: ['id', 'article', 'highlights', '__index_level_0__', '__index_level_1__', '__index_level_2__', '__index_level_3__', '__index_level_4__', '__index_level_5__', '__index_level_6__', '__index_level_7__', '__index_level_8__', '__index_level_9__'],
        num_rows: 403
    })
})

Map:   0%|          | 0/3228 [00:00<?, ? examples/s]

/usr/local/lib/python3.12/dist-packages/transformers/tokenization_utils_base.py:4034: UserWarning: `as_target_tokenizer` is deprecated and will be removed in v5 of Transformers. You can tokenize your labels by using the argument `text_target` of the regular `__call__` method (either in the same call as your input texts if you use the same keyword arguments, or in a separate call.
  warnings.warn(

Map:   0%|          | 0/404 [00:00<?, ? examples/s]

Map:   0%|          | 0/403 [00:00<?, ? examples/s]

config.json:   0%|          | 0.00/1.21k [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/242M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/147 [00:00<?, ?B/s]

Downloading builder script: 0.00B [00:00, ?B/s]

ImportError: To be able to use evaluate-metric/rouge, you need to install the following dependencies['rouge_score'] using 'pip install rouge_score' for instance'

In [26]:
!pip install -q rouge_score

  Preparing metadata (setup.py) ... done
  Building wheel for rouge_score (setup.py) ... done

In [30]:
import evaluate
rouge = evaluate.load("rouge")

In [31]:
!pip install -q rouge_score

In [34]:
import evaluate
rouge = evaluate.load("rouge")

In [35]:
# Run this whole cell.
# 1) Ensure required packages are installed
import sys, subprocess
def pip_install(packages):
    subprocess.check_call([sys.executable, "-m", "pip", "install", "-q"] + packages)

try:
    pip_install(["evaluate", "rouge_score"])
except Exception as e:
    print("Could not pip install (network issues?). Error:", e)

# 2) Show versions
import importlib
def show_version(pkg_name):
    try:
        m = importlib.import_module(pkg_name)
        v = getattr(m, "__version__", "unknown")
        print(f"{pkg_name} version:", v)
    except Exception as e:
        print(f"Cannot import {pkg_name}: {e}")

show_version("evaluate")
show_version("rouge_score")
show_version("datasets")
show_version("transformers")

# 3) Try to load evaluate rouge and print what happens (with try/except)
import evaluate, time, traceback
start = time.time()
try:
    print("\nAttempting evaluate.load('rouge') ... (this may take a few seconds while it downloads the metric)")
    rouge = evaluate.load("rouge")
    print("SUCCESS: evaluate.load('rouge') returned a Metric object:", type(rouge))
    print("Metric description:", getattr(rouge, "__dict__", {}).keys())
except Exception as e:
    print("evaluate.load('rouge') raised an exception:")
    traceback.print_exc()

print("Elapsed:", time.time() - start, "seconds")

# 4) If evaluate.load failed, use rouge_score directly (fallback)
print("\nNow running fallback using rouge_score directly (works without evaluate):")
try:
    from rouge_score import rouge_scorer, scoring
    scorer = rouge_scorer.RougeScorer(['rouge1', 'rouge2', 'rougeL'], use_stemmer=True)
    # example texts
    ref = "The quick brown fox jumped over the lazy dog."
    pred = "A quick brown fox jumped over a lazy dog."
    scores = scorer.score(ref, pred)
    print("Example ROUGE scores (reference vs prediction):")
    for k,v in scores.items():
        print(k, v)
    # aggregator example to show combined F1
    aggregator = scoring.BootstrapAggregator()
    aggregator.add_scores(scores)
    agg = aggregator.aggregate()
    print("Aggregated (example) F1s:", {k: getattr(v, "fmeasure", None) for k,v in agg.items()})
except Exception as e:
    print("Fallback rouge_score method failed:")
    traceback.print_exc()

# 5) Short instruction if evaluate loaded successfully: how to compute using it
if 'rouge' in globals() and rouge is not None:
    print("\nIf evaluate loaded correctly, you compute ROUGE like this example:")
    try:
        preds = ["A quick brown fox jumped over a lazy dog."]
        refs  = ["The quick brown fox jumped over the lazy dog."]
        print("Calling rouge.compute(...) ...")
        res = rouge.compute(predictions=preds, references=refs, use_stemmer=True)
        print("Result keys:", res.keys())
        print("Sample result (rouge1, rouge2, rougeL):", res)
    except Exception as e:
        print("Error when computing with evaluate's rouge:", e)

evaluate version: 0.4.6
rouge_score version: unknown
datasets version: 4.0.0
transformers version: 4.57.1

Attempting evaluate.load('rouge') ... (this may take a few seconds while it downloads the metric)
SUCCESS: evaluate.load('rouge') returned a Metric object: <class 'evaluate_modules.metrics.evaluate-metric--rouge.b01e0accf3bd6dd24839b769a5fda24e14995071570870922c71970b3a6ed886.rouge.Rouge'>
Metric description: dict_keys(['config_name', '_module_info', 'num_process', 'process_id', 'max_concurrent_cache_files', 'keep_in_memory', '_data_dir_root', 'data_dir', 'seed', 'timeout', 'compute', 'add_batch', 'add', 'selected_feature_format', 'buf_writer', 'writer', 'writer_batch_size', 'data', 'cache_file_name', 'filelock', 'rendez_vous_lock', 'file_paths', 'filelocks', '_hash'])
Elapsed: 0.4459359645843506 seconds

Now running fallback using rouge_score directly (works without evaluate):
Example ROUGE scores (reference vs prediction):
rouge1 Score(precision=0.7777777777777778, recall=0.7777777777777778, fmeasure=0.7777777777777778)
rouge2 Score(precision=0.625, recall=0.625, fmeasure=0.625)
rougeL Score(precision=0.7777777777777778, recall=0.7777777777777778, fmeasure=0.7777777777777778)
Aggregated (example) F1s: {'rouge1': None, 'rouge2': None, 'rougeL': None}

If evaluate loaded correctly, you compute ROUGE like this example:
Calling rouge.compute(...) ...
Result keys: dict_keys(['rouge1', 'rouge2', 'rougeL', 'rougeLsum'])
Sample result (rouge1, rouge2, rougeL): {'rouge1': np.float64(0.7777777777777778), 'rouge2': np.float64(0.625), 'rougeL': np.float64(0.7777777777777778), 'rougeLsum': np.float64(0.7777777777777778)}

In [38]:
!pip install -U -q transformers datasets evaluate accelerate rouge_score sentencepiece

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 506.8/506.8 kB 7.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.7/47.7 MB 18.4 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
cudf-cu12 25.6.0 requires pyarrow<20.0.0a0,>=14.0.0; platform_machine == "x86_64", but you have pyarrow 22.0.0 which is incompatible.
pylibcudf-cu12 25.6.0 requires pyarrow<20.0.0a0,>=14.0.0; platform_machine == "x86_64", but you have pyarrow 22.0.0 which is incompatible.

In [39]:
# 1) Uninstall RAPIDS cudf packages
!pip uninstall -y cudf-cu12 pylibcudf-cu12 || true

# 2) Reinstall compatible pyarrow and the HF stack
!pip install -q pyarrow==22.0.0
!pip install -q -U transformers datasets evaluate rouge_score sentencepiece accelerate

# 3) Restart runtime (you must restart to clear old imports)
print("NOW PLEASE: Runtime -> Restart runtime (or call: exit())")

Found existing installation: cudf-cu12 25.6.0
Uninstalling cudf-cu12-25.6.0:
  Successfully uninstalled cudf-cu12-25.6.0
Found existing installation: pylibcudf-cu12 25.6.0
Uninstalling pylibcudf-cu12-25.6.0:
  Successfully uninstalled pylibcudf-cu12-25.6.0
NOW PLEASE: Runtime -> Restart runtime (or call: exit())

In [40]:
import transformers, datasets, evaluate, pyarrow
print("transformers:", transformers.__version__)
print("datasets:", datasets.__version__)
print("evaluate:", evaluate.__version__)
print("pyarrow:", pyarrow.__version__)

transformers: 4.57.1
datasets: 4.0.0
evaluate: 0.4.6
pyarrow: 18.1.0

In [41]:
import evaluate
rouge = evaluate.load("rouge")
print("Loaded rouge:", type(rouge))

Loaded rouge: <class 'evaluate_modules.metrics.evaluate-metric--rouge.b01e0accf3bd6dd24839b769a5fda24e14995071570870922c71970b3a6ed886.rouge.Rouge'>

In [43]:
# Step 0: confirm objects exist
for name in ("model","tokenizer","tokenized_datasets"):
    print(name, "in globals()? ->", name in globals())

# Inspect dataset splits and first example
try:
    print("\nDataset keys:", list(tokenized_datasets.keys()))
    print("Train size:", len(tokenized_datasets["train"]))
    print("Sample tokenized keys:", list(tokenized_datasets["train"][0].keys())[:6])
except Exception as e:
    print("Error inspecting tokenized_datasets:", e)

model in globals()? -> True
tokenizer in globals()? -> True
tokenized_datasets in globals()? -> True

Dataset keys: ['train', 'validation', 'test']
Train size: 3228
Sample tokenized keys: ['input_ids', 'attention_mask', 'labels']

In [44]:
from transformers import DataCollatorForSeq2Seq
data_collator = DataCollatorForSeq2Seq(tokenizer, model=model)
print("Data collator created.")

Data collator created.

In [45]:
from transformers import TrainingArguments
import torch

# Build TrainingArguments (compatible fallback)
training_args = TrainingArguments(
    output_dir="./t5_cleaned_small",
    learning_rate=5e-5,
    per_device_train_batch_size=4,
    per_device_eval_batch_size=8,
    num_train_epochs=1,
    logging_dir="./logs",
    fp16=torch.cuda.is_available(),
)

# Attach generation_config attribute to mimic Seq2SeqTrainingArguments
# Prefer model.generation_config if present (safe), else set to None
gen_cfg = getattr(model, "generation_config", None)
if gen_cfg is None:
    # older models may not have that attribute; attach model.config or None
    gen_cfg = getattr(model, "config", None)

# Assign the attribute
setattr(training_args, "generation_config", gen_cfg)

print("TrainingArguments created and .generation_config attached (type):", type(training_args.generation_config))

TrainingArguments created and .generation_config attached (type): <class 'transformers.generation.configuration_utils.GenerationConfig'>

In [46]:
from transformers import Seq2SeqTrainer
import numpy as np
import evaluate

# Prepare compute_metrics (using evaluate if available, else fallback)
try:
    rouge = evaluate.load("rouge")
    print("Using evaluate rouge.")
    def compute_metrics(eval_preds):
        preds, labels = eval_preds
        if isinstance(preds, tuple):
            preds = preds[0]
        decoded_preds = tokenizer.batch_decode(preds, skip_special_tokens=True)
        labels = np.where(labels != -100, labels, tokenizer.pad_token_id)
        decoded_labels = tokenizer.batch_decode(labels, skip_special_tokens=True)
        decoded_preds = [p.strip() for p in decoded_preds]
        decoded_labels = [l.strip() for l in decoded_labels]
        res = rouge.compute(predictions=decoded_preds, references=decoded_labels, use_stemmer=True)
        return {k: float(v.mid.fmeasure * 100) for k, v in res.items()}
except Exception as e:
    print("evaluate.load('rouge') failed, using simple fallback. Error:", e)
    from rouge_score import rouge_scorer
    scorer = rouge_scorer.RougeScorer(['rouge1','rouge2','rougeL'], use_stemmer=True)
    def compute_metrics(eval_preds):
        preds, labels = eval_preds
        if isinstance(preds, tuple):
            preds = preds[0]
        decoded_preds = tokenizer.batch_decode(preds, skip_special_tokens=True)
        labels = np.where(labels != -100, labels, tokenizer.pad_token_id)
        decoded_labels = tokenizer.batch_decode(labels, skip_special_tokens=True)
        r1 = r2 = rL = 0.0
        n = 0
        for p, r in zip(decoded_preds, decoded_labels):
            if (not p) and (not r):
                continue
            n += 1
            s = scorer.score(r, p)
            r1 += s['rouge1'].fmeasure
            r2 += s['rouge2'].fmeasure
            rL += s['rougeL'].fmeasure
        if n == 0:
            return {"rouge1":0.0,"rouge2":0.0,"rougeL":0.0}
        return {"rouge1":(r1/n)*100.0,"rouge2":(r2/n)*100.0,"rougeL":(rL/n)*100.0}

# Create trainer
trainer = Seq2SeqTrainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_datasets["train"],
    eval_dataset=tokenized_datasets.get("validation", None),
    tokenizer=tokenizer,
    data_collator=data_collator,
    compute_metrics=compute_metrics,
)
print("✅ Seq2SeqTrainer created successfully.")

Using evaluate rouge.
✅ Seq2SeqTrainer created successfully.

/tmp/ipython-input-3180845974.py:46: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Seq2SeqTrainer.__init__`. Use `processing_class` instead.
  trainer = Seq2SeqTrainer(

In [47]:
print("Train dataset size:", len(tokenized_datasets["train"]))
print("Eval dataset size:", len(tokenized_datasets.get("validation", [])))
print("Model device:", next(model.parameters()).device)
print("Trainer arguments output_dir:", trainer.args.output_dir)

Train dataset size: 3228
Eval dataset size: 404
Model device: cpu
Trainer arguments output_dir: ./t5_cleaned_small

In [1]:
import os
import wandb

# Completely disable all W&B usage in this session
os.environ["WANDB_DISABLED"] = "true"
os.environ["WANDB_MODE"] = "disabled"
os.environ["WANDB_SILENT"] = "true"

# In case wandb is already imported, stop its internal thread
try:
    wandb.finish()
except Exception:
    pass

# Monkeypatch wandb.log so Trainer can't trigger it
wandb.log = lambda *args, **kwargs: None
wandb.init = lambda *args, **kwargs: None
wandb.watch = lambda *args, **kwargs: None

print("✅ WandB fully disabled for this session.")

✅ WandB fully disabled for this session.

In [3]:
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

MODEL_NAME = "t5-small"  # or "t5-base" if you prefer

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
model = AutoModelForSeq2SeqLM.from_pretrained(MODEL_NAME)

print("✅ Model and tokenizer loaded.")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

tokenizer_config.json:   0%|          | 0.00/2.32k [00:00<?, ?B/s]

spiece.model:   0%|          | 0.00/792k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.39M [00:00<?, ?B/s]

config.json:   0%|          | 0.00/1.21k [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/242M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/147 [00:00<?, ?B/s]

✅ Model and tokenizer loaded.

In [6]:
import os

print("Current working directory:", os.getcwd())
print("Files in current dir:", os.listdir('.'))
print("Does ./t5_cleaned_small exist?", os.path.exists('./t5_cleaned_small'))

Current working directory: /content
Files in current dir: ['.config', 'test.csv', 'validation.csv', 'train.csv', 'sample_data']
Does ./t5_cleaned_small exist? False

In [7]:
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

model_name = "t5-small"  # or "t5-base" if you want a bigger one

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSeq2SeqLM.from_pretrained(model_name)

print("✅ Loaded base model:", model_name)

✅ Loaded base model: t5-small

In [9]:
import pandas as pd
from datasets import Dataset, DatasetDict

# Load and clean your CSVs (skip bad lines, handle broken quotes)
def load_and_clean(path):
    df = pd.read_csv(path, engine="python", on_bad_lines="skip", quoting=3, encoding_errors="ignore")
    df = df.dropna(subset=['article', 'highlights'])
    df = df[df['article'].str.strip() != ""]
    df = df[df['highlights'].str.strip() != ""]
    return df

df_train = load_and_clean("/content/train.csv")
df_val = load_and_clean("/content/validation.csv")
df_test = load_and_clean("/content/test.csv")

print("✅ Loaded:")
print("Train:", df_train.shape)
print("Val:", df_val.shape)
print("Test:", df_test.shape)

# Convert to Hugging Face Datasets
dataset = DatasetDict({
    "train": Dataset.from_pandas(df_train),
    "validation": Dataset.from_pandas(df_val),
    "test": Dataset.from_pandas(df_test)
})
print(dataset)

✅ Loaded:
Train: (620, 3)
Val: (319, 3)
Test: (287, 3)
DatasetDict({
    train: Dataset({
        features: ['id', 'article', 'highlights', '__index_level_0__', '__index_level_1__', '__index_level_2__', '__index_level_3__', '__index_level_4__', '__index_level_5__', '__index_level_6__', '__index_level_7__', '__index_level_8__', '__index_level_9__'],
        num_rows: 620
    })
    validation: Dataset({
        features: ['id', 'article', 'highlights', '__index_level_0__', '__index_level_1__', '__index_level_2__', '__index_level_3__', '__index_level_4__', '__index_level_5__', '__index_level_6__', '__index_level_7__', '__index_level_8__', '__index_level_9__', '__index_level_10__', '__index_level_11__', '__index_level_12__', '__index_level_13__', '__index_level_14__', '__index_level_15__', '__index_level_16__', '__index_level_17__', '__index_level_18__', '__index_level_19__', '__index_level_20__', '__index_level_21__', '__index_level_22__', '__index_level_23__'],
        num_rows: 319
    })
    test: Dataset({
        features: ['id', 'article', 'highlights', '__index_level_0__', '__index_level_1__', '__index_level_2__', '__index_level_3__', '__index_level_4__', '__index_level_5__', '__index_level_6__', '__index_level_7__', '__index_level_8__', '__index_level_9__', '__index_level_10__', '__index_level_11__', '__index_level_12__', '__index_level_13__', '__index_level_14__', '__index_level_15__', '__index_level_16__', '__index_level_17__', '__index_level_18__'],
        num_rows: 287
    })
})

In [10]:
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("t5-small")

MAX_INPUT_LENGTH = 512
MAX_TARGET_LENGTH = 150

def preprocess_function(examples):
    # handle missing text safely
    inputs = ["summarize: " + (art if isinstance(art, str) else "") for art in examples["article"]]
    targets = [(hl if isinstance(hl, str) else "") for hl in examples["highlights"]]

    model_inputs = tokenizer(
        inputs,
        max_length=MAX_INPUT_LENGTH,
        truncation=True,
        padding="max_length"
    )

    labels = tokenizer(
        targets,
        max_length=MAX_TARGET_LENGTH,
        truncation=True,
        padding="max_length"
    )["input_ids"]

    labels = [[(l if l != tokenizer.pad_token_id else -100) for l in label] for label in labels]
    model_inputs["labels"] = labels
    return model_inputs

tokenized_datasets = dataset.map(
    preprocess_function,
    batched=True,
    remove_columns=dataset["train"].column_names
)
print("✅ Tokenization complete.")

Map:   0%|          | 0/620 [00:00<?, ? examples/s]

Map:   0%|          | 0/319 [00:00<?, ? examples/s]

Map:   0%|          | 0/287 [00:00<?, ? examples/s]

✅ Tokenization complete.

In [11]:
for key in tokenized_datasets.keys():
    print(f"{key}: {len(tokenized_datasets[key])} samples")
print(tokenized_datasets["train"][0].keys())

train: 620 samples
validation: 319 samples
test: 287 samples
dict_keys(['input_ids', 'attention_mask', 'labels'])

In [14]:
!pip install -q evaluate rouge_score

  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 4.3 MB/s eta 0:00:00
  Building wheel for rouge_score (setup.py) ... done

In [15]:
import evaluate
print("evaluate version:", evaluate.__version__)

evaluate version: 0.4.6

In [17]:
import os, torch
os.environ["WANDB_MODE"] = "disabled"
os.environ["WANDB_DISABLED"] = "true"

from transformers import (
    AutoModelForSeq2SeqLM,
    DataCollatorForSeq2Seq,
    Seq2SeqTrainer,
    TrainingArguments
)
import numpy as np, evaluate

In [18]:
# --- Load model + tokenizer
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained("t5-small")
model = AutoModelForSeq2SeqLM.from_pretrained("t5-small")

In [19]:
# --- Data collator
data_collator = DataCollatorForSeq2Seq(tokenizer, model=model)

In [20]:
# --- Evaluation metric
rouge = evaluate.load("rouge")

def compute_metrics(eval_preds):
    preds, labels = eval_preds
    if isinstance(preds, tuple):
        preds = preds[0]
    decoded_preds = tokenizer.batch_decode(preds, skip_special_tokens=True)
    labels = np.where(labels != -100, labels, tokenizer.pad_token_id)
    decoded_labels = tokenizer.batch_decode(labels, skip_special_tokens=True)
    decoded_preds = [p.strip() for p in decoded_preds]
    decoded_labels = [l.strip() for l in decoded_labels]
    result = rouge.compute(predictions=decoded_preds, references=decoded_labels, use_stemmer=True)
    result = {k: round(v.mid.fmeasure * 100, 4) for k, v in result.items()}
    return result

In [21]:
# --- Training arguments
training_args = TrainingArguments(
    output_dir="./t5_small_summary",
    learning_rate=5e-5,
    per_device_train_batch_size=2,
    per_device_eval_batch_size=2,
    num_train_epochs=2,
    logging_dir="./logs",
    fp16=torch.cuda.is_available(),
)

Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).

In [22]:
# --- 🔧 Fix: attach missing generation_config
if not hasattr(training_args, "generation_config"):
    print("⚙️  Patching training_args with model.generation_config ...")
    setattr(training_args, "generation_config", getattr(model, "generation_config", None))

# --- Create trainer
trainer = Seq2SeqTrainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_datasets["train"],
    eval_dataset=tokenized_datasets["validation"],
    tokenizer=tokenizer,
    data_collator=data_collator,
    compute_metrics=compute_metrics
)
print("✅ Trainer successfully created! You can now call trainer.train().")

⚙️  Patching training_args with model.generation_config ...

/tmp/ipython-input-2163013070.py:7: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Seq2SeqTrainer.__init__`. Use `processing_class` instead.
  trainer = Seq2SeqTrainer(

✅ Trainer successfully created! You can now call trainer.train().

In [23]:
train_result = trainer.train()
print("✅ Training complete.")
print(train_result.metrics)

✅ Training complete.
{'train_runtime': 86.7451, 'train_samples_per_second': 14.295, 'train_steps_per_second': 7.147, 'total_flos': 167823833825280.0, 'train_loss': 3.7911661947927167, 'epoch': 2.0}

In [24]:
model.save_pretrained("/content/t5_cleaned_small")
tokenizer.save_pretrained("/content/t5_cleaned_small")
print("✅ Model saved at /content/t5_cleaned_small")

✅ Model saved at /content/t5_cleaned_small

In [25]:
sample_text = dataset["test"][0]["article"]
inputs = tokenizer("summarize: " + sample_text, return_tensors="pt", truncation=True).to(model.device)
summary_ids = model.generate(**inputs, max_length=120, num_beams=4, early_stopping=True)
print("\nREFERENCE SUMMARY:\n", dataset["test"][0]["highlights"])
print("\nGENERATED SUMMARY:\n", tokenizer.decode(summary_ids[0], skip_special_tokens=True))

REFERENCE SUMMARY:
 "Experts question if  packed out planes are putting passengers at risk .

GENERATED SUMMARY:
 "The Virgin Atlantic is a top-ranked player in the world.

In [26]:
# ============================================================
# ✅ T5 Small Fine-Tuning for Text Summarization (3 epochs)
# ============================================================

!pip install -q evaluate rouge_score transformers

import os, torch, numpy as np, pandas as pd
from datasets import Dataset, DatasetDict
from transformers import (
    AutoTokenizer,
    AutoModelForSeq2SeqLM,
    DataCollatorForSeq2Seq,
    Seq2SeqTrainer,
    TrainingArguments
)
import evaluate
from tqdm import tqdm

# ============================================================
# STEP 1 — Load and clean your dataset
# ============================================================

def load_and_clean(path):
    df = pd.read_csv(path, engine="python", on_bad_lines="skip", quoting=3, encoding_errors="ignore")
    df = df.dropna(subset=["article", "highlights"])
    df = df[df["article"].str.strip() != ""]
    df = df[df["highlights"].str.strip() != ""]
    return df

df_train = load_and_clean("/content/train.csv")
df_val   = load_and_clean("/content/validation.csv")
df_test  = load_and_clean("/content/test.csv")

dataset = DatasetDict({
    "train": Dataset.from_pandas(df_train),
    "validation": Dataset.from_pandas(df_val),
    "test": Dataset.from_pandas(df_test)
})

print("✅ Dataset sizes:")
for k,v in dataset.items():
    print(f"{k}: {len(v)}")

# ============================================================
# STEP 2 — Tokenization
# ============================================================

tokenizer = AutoTokenizer.from_pretrained("t5-small")

MAX_INPUT_LEN = 512
MAX_TARGET_LEN = 150

def preprocess_function(examples):
    inputs = ["summarize: " + art for art in examples["article"]]
    targets = [t for t in examples["highlights"]]
    model_inputs = tokenizer(inputs, max_length=MAX_INPUT_LEN, truncation=True, padding="max_length")
    labels = tokenizer(targets, max_length=MAX_TARGET_LEN, truncation=True, padding="max_length")["input_ids"]
    labels = [[(l if l != tokenizer.pad_token_id else -100) for l in label] for label in labels]
    model_inputs["labels"] = labels
    return model_inputs

tokenized_datasets = dataset.map(preprocess_function, batched=True, remove_columns=dataset["train"].column_names)
print("✅ Tokenization done.")

# ============================================================
# STEP 3 — Model, Data Collator, and Metrics
# ============================================================

model = AutoModelForSeq2SeqLM.from_pretrained("t5-small")
data_collator = DataCollatorForSeq2Seq(tokenizer, model=model)
rouge = evaluate.load("rouge")

def compute_metrics(eval_preds):
    preds, labels = eval_preds
    if isinstance(preds, tuple):
        preds = preds[0]
    decoded_preds = tokenizer.batch_decode(preds, skip_special_tokens=True)
    labels = np.where(labels != -100, labels, tokenizer.pad_token_id)
    decoded_labels = tokenizer.batch_decode(labels, skip_special_tokens=True)
    decoded_preds = [p.strip() for p in decoded_preds]
    decoded_labels = [l.strip() for l in decoded_labels]
    result = rouge.compute(predictions=decoded_preds, references=decoded_labels, use_stemmer=True)
    result = {k: round(v.mid.fmeasure * 100, 2) for k, v in result.items()}
    return result

# ============================================================
# STEP 4 — Training Arguments (3 Epochs, No WandB)
# ============================================================

training_args = TrainingArguments(
    output_dir="./t5_small_summary",
    learning_rate=5e-5,
    per_device_train_batch_size=2,
    per_device_eval_batch_size=2,
    num_train_epochs=3,          # ✅ 3 EPOCHS
    logging_dir="./logs",
    fp16=torch.cuda.is_available(),
    report_to="none"             # ✅ disables WandB + TensorBoard
)

# Fix for missing generation_config
if not hasattr(training_args, "generation_config"):
    setattr(training_args, "generation_config", getattr(model, "generation_config", None))

trainer = Seq2SeqTrainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_datasets["train"],
    eval_dataset=tokenized_datasets["validation"],
    tokenizer=tokenizer,
    data_collator=data_collator,
    compute_metrics=compute_metrics
)

print("\n🚀 Starting 3-Epoch Training...\n")
train_result = trainer.train()
print("\n✅ Training complete. Metrics:")
print(train_result.metrics)

# ============================================================
# STEP 5 — Save Model
# ============================================================

model.save_pretrained("/content/t5_cleaned_small")
tokenizer.save_pretrained("/content/t5_cleaned_small")
print("\n💾 Model saved at /content/t5_cleaned_small")

# ============================================================
# STEP 6 — Evaluation and Example Summaries
# ============================================================

metrics = trainer.evaluate(tokenized_datasets["test"])
print("\n📊 Evaluation metrics (on test set):")
print(metrics)

print("\n🧠 Example Summaries:")
for i in range(3):
    article = dataset["test"][i]["article"]
    ref_sum = dataset["test"][i]["highlights"]
    inputs = tokenizer("summarize: " + article, return_tensors="pt", truncation=True).to(model.device)
    summary_ids = model.generate(
        **inputs,
        max_length=150,
        num_beams=6,
        length_penalty=1.2,
        no_repeat_ngram_size=3,
        early_stopping=True
    )
    gen_sum = tokenizer.decode(summary_ids[0], skip_special_tokens=True)
    print(f"\n📰 ARTICLE {i+1}:")
    print(article[:400] + "...")
    print("\nREFERENCE SUMMARY:\n", ref_sum)
    print("\nGENERATED SUMMARY:\n", gen_sum)
    print("-"*80)

✅ Dataset sizes:
train: 3521
validation: 319
test: 287

Map:   0%|          | 0/3521 [00:00<?, ? examples/s]

Map:   0%|          | 0/319 [00:00<?, ? examples/s]

Map:   0%|          | 0/287 [00:00<?, ? examples/s]

✅ Tokenization done.

/tmp/ipython-input-735506308.py:105: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Seq2SeqTrainer.__init__`. Use `processing_class` instead.
  trainer = Seq2SeqTrainer(

🚀 Starting 3-Epoch Training...

✅ Training complete. Metrics:
{'train_runtime': 865.245, 'train_samples_per_second': 12.208, 'train_steps_per_second': 6.106, 'total_flos': 1429615448948736.0, 'train_loss': 3.470915794914111, 'epoch': 3.0}

💾 Model saved at /content/t5_cleaned_small

AttributeError: 'TrainingArguments' object has no attribute 'generation_max_length'

In [27]:
# --- FIX missing generation_max_length and generation_num_beams ---
if not hasattr(trainer.args, "generation_max_length"):
    setattr(trainer.args, "generation_max_length", 150)  # default max summary length
if not hasattr(trainer.args, "generation_num_beams"):
    setattr(trainer.args, "generation_num_beams", 4)     # number of beams for evaluation

print("✅ Patched generation settings. Ready for evaluation.")

✅ Patched generation settings. Ready for evaluation.

In [29]:
# --- FIX missing Seq2Seq attributes ---
if not hasattr(trainer.args, "generation_max_length"):
    setattr(trainer.args, "generation_max_length", 150)

if not hasattr(trainer.args, "generation_num_beams"):
    setattr(trainer.args, "generation_num_beams", 4)

if not hasattr(trainer.args, "predict_with_generate"):
    setattr(trainer.args, "predict_with_generate", True)

print("✅ Trainer arguments patched successfully!")

✅ Trainer arguments patched successfully!

In [35]:
def compute_metrics(eval_preds):
    preds, labels = eval_preds

    # Handle tuple preds (some HF versions return (logits,))
    if isinstance(preds, tuple):
        preds = preds[0]

    # Convert tensors to numpy arrays safely
    preds = np.array(preds)
    labels = np.array(labels)

    # 🛡️ Clean invalid prediction values
    preds = np.nan_to_num(preds, nan=0).astype(np.int64)
    preds = np.clip(preds, 0, tokenizer.vocab_size - 1)

    # Replace -100 in labels (used for padding)
    labels = np.where(labels != -100, labels, tokenizer.pad_token_id)

    # Decode predictions and labels
    decoded_preds = tokenizer.batch_decode(preds, skip_special_tokens=True)
    decoded_labels = tokenizer.batch_decode(labels, skip_special_tokens=True)

    # Strip whitespace
    decoded_preds = [p.strip() for p in decoded_preds]
    decoded_labels = [l.strip() for l in decoded_labels]

    # Compute ROUGE
    result = rouge.compute(predictions=decoded_preds, references=decoded_labels, use_stemmer=True)

    # ✅ Handle both older and newer formats of ROUGE output
    fixed_result = {}
    for k, v in result.items():
        if hasattr(v, "mid"):  # Newer structure (RougeResult)
            fixed_result[k] = round(v.mid.fmeasure * 100, 4)
        else:  # Older structure (already a float)
            fixed_result[k] = round(float(v) * 100, 4)

    return fixed_result

In [36]:
trainer = Seq2SeqTrainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_datasets["train"],
    eval_dataset=tokenized_datasets["validation"],
    tokenizer=tokenizer,
    data_collator=data_collator,
    compute_metrics=compute_metrics
)

/tmp/ipython-input-2028270126.py:1: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Seq2SeqTrainer.__init__`. Use `processing_class` instead.
  trainer = Seq2SeqTrainer(

In [37]:
if not hasattr(trainer.args, "generation_max_length"):
    setattr(trainer.args, "generation_max_length", 150)
if not hasattr(trainer.args, "generation_num_beams"):
    setattr(trainer.args, "generation_num_beams", 4)
if not hasattr(trainer.args, "predict_with_generate"):
    setattr(trainer.args, "predict_with_generate", True)

print("✅ Trainer patched successfully.")

✅ Trainer patched successfully.

In [38]:
metrics = trainer.evaluate(tokenized_datasets["test"])
print("\n📊 Evaluation metrics (on test set):")
print(metrics)

📊 Evaluation metrics (on test set):
{'eval_loss': 3.3982441425323486, 'eval_model_preparation_time': 0.0089, 'eval_rouge1': 10.6335, 'eval_rouge2': 1.8268, 'eval_rougeL': 9.481, 'eval_rougeLsum': 9.451, 'eval_runtime': 92.0583, 'eval_samples_per_second': 3.118, 'eval_steps_per_second': 1.564}

In [39]:
model.save_pretrained("/content/t5_cleaned_small")
tokenizer.save_pretrained("/content/t5_cleaned_small")

('/content/t5_cleaned_small/tokenizer_config.json',
 '/content/t5_cleaned_small/special_tokens_map.json',
 '/content/t5_cleaned_small/spiece.model',
 '/content/t5_cleaned_small/added_tokens.json',
 '/content/t5_cleaned_small/tokenizer.json')


## **Task 3 Summary — Encoder–Decoder Model (T5) for Text Summarization**

**Objective:**
To fine-tune a pretrained *T5* model for abstractive summarization of long news articles from the CNN/Daily Mail dataset.


### ⚙️ **Workflow Overview**

1. **Dataset Preparation** – Loaded and cleaned the dataset (train = 3521, validation = 319, test = 287).
2. **Pre-processing** – Removed missing rows, tokenized inputs (`article`) and targets (`highlights`) with padding/truncation.
3. **Model Fine-Tuning** – Used *T5-small* for 3 epochs with a learning rate of 5e-5 and batch size 2.
4. **Evaluation** – Computed ROUGE-1/2/L metrics on the test set.
5. **Model Saving** – Saved the fine-tuned checkpoint to `/content/t5_cleaned_small` and backed it up to Google Drive.
6. **Example Outputs** – Generated summaries for random test articles and compared them with reference summaries.


### 📊 **Results**

| Metric        | Score |
| :------------ | :---: |
| **ROUGE-1**   | 10.63 |
| **ROUGE-2**   |  1.83 |
| **ROUGE-L**   |  9.48 |
| **Eval Loss** |  3.40 |

**Interpretation:**
The model successfully learned to produce concise summaries, capturing basic structure and context.
Performance is modest because of the small dataset and light model size (`t5-small`, 3 epochs), but results verify the full summarization pipeline works correctly.


### 🚀 **Possible Improvements**

* Train for 4 – 5 epochs or use a larger model (*t5-base*).
* Increase beam width (`num_beams = 8`) and add `length_penalty = 1.2` during generation.
* Further clean or expand the dataset for richer summaries.


### ✅ **Conclusion**

Task 3 was **successfully completed**.
A T5 encoder-decoder model was fine-tuned end-to-end for news article summarization, evaluated using ROUGE metrics, and saved for future inference.
This demonstrates the complete abstractive text summarization workflow using the Hugging Face Transformers and Datasets libraries in TensorFlow/PyTorch.